---
title: "HW1"
author: "Zheng Ding, Yanyu Liu, Joshua Fink"
date: "September 12, 2014"
output: html_document
---
## Task 1 - Parse
```{r echo = TRUE}
#build a NA matrix
data = matrix(NA,nrow=193,ncol=14)
colnames(data) = list("ID", "pig", "class", "pid", "mid", "pname", "pteam", "ptime", "paddtime", "ptype", "pteamimg", "pmatch", "style.right", "style.top")

#read data
d = readLines("~cr173/Sta523/data/world_cup_goals_raw.txt")
library(stringr)
idRead = str_match_all(d, " id=\"([a-z0-9]*)\"")
pigRead = str_match_all(d, " pig=\"([0-9]*)\"")
classRead = str_match_all(d, " class=\"([a-z ]*)\"")
pidRead = str_match_all(d, " pid=\"([0-9]*)\"")
midRead = str_match_all(d, " mid=\"([0-9]*)\"")
pnameRead = str_match_all(d, " pname=\"(.*)\" pteam=")
pteamRead = str_match_all(d, " pteam=\"(.*)\" ptime=")
ptimeRead = str_match_all(d, " ptime=\"([0-9 ]*)\"")
paddtimeRead = str_match_all(d, " paddtime=\"([0-9 ]*)\"")
ptypeRead = str_match_all(d, " ptype=\"(.*)\" pteamimg=")
pteamimgRead = str_match_all(d, " pteamimg=\"([a-z/a-z.a-z ]*)\"")
pmatchRead = str_match_all(d, " pmatch=\"(.*)\" style=")
style.leftRead = str_match_all(d, "left: ([0-9]*)px;")
style.topRead = str_match_all(d, "top: ([0-9]*)px.")
style.rightRead = str_match_all(d, "right: ([0-9]*)px;")

#combine left and right data; left is only available in the first row, so in the intergrated column, only 1st row records left data, and we will transform it to right later 
style.rightRead[[1]] = style.leftRead[[1]]

#combine all data and pull data in the NA matrix
Read = list(idRead, pigRead, classRead, pidRead, midRead, pnameRead, pteamRead, ptimeRead, paddtimeRead, ptypeRead, pteamimgRead, pmatchRead, style.rightRead, style.topRead)

for (i in 1:14)
  {
  for (j in 1:193)
    {
    data[j,i] = Read[[i]][[j]][,2]
    }
  }

#Based on that 1st and 30th row have the same style.top and their location in the visualization website (http://ejoh.se/worldcup2014/goals/), we think style.top measures the distance between shot location and top goal line. Similarly, style.right and style.left measure the distance between shot location and right or left touch line respectively. Besides, the 1st row (player name: Joel Matipand) and 84th row (player name: Mathieu Valbuena) should have the same style.right, based on the location of visualization website. So the whole length of goal line should be 1st style.left + 84th style.right = 990.
#transform style.left to style.right in the 1st row (Before the transformation, style.right[1] in fact means style.left[1]) 
data[,13:14] = as.numeric(unlist(data[,13:14]))
data[1,13] = 990 - data[1,13]

#build final dataframe contained what we need: pig (where the ball entered the goal), mid (match number), pname (player), pteam (team), ptime (time), paddtime (time if goal in extra time), ptype (goal or penalty), style.right and style.left (shot location)
Data = data.frame(data[,c(2,5,6,7,8,9,10,13,14)])

#set type of each column
data$ptime=as.numeric(data$ptime)
data$paddtime=as.numeric(data$paddtime)
str(data)
```


## Task 3 - Translate
```{r echo = TRUE}
library(rjson)
for (i in 1:193) {
  cat(toJSON(Data[i,]))
  i = i + 1
}
```